[NRLF 296] onboarding changes
NHSDigital/NRLF pull request #189
Opened 2023-03-13 11:12 UTC by Rohoolio

Adjustments to the readme

2023-03-13 12:07 UTC, nomad3k approved these changes

2023-03-15 11:43 UTC, andrewrae5-nhs requested changes
This is good - there are a few comments that need to be addressed though. 

also, it might be worthwhile mentioning the [confluence article ](https://nhsd-confluence.digital.nhs.uk/display/CLP/NRLF+-+Developer+Onboarding)at the top, as there are more details in that. 

Actually, I would say that you could probably just get rid of the rest after the quick install and re-direct them to the confluence article, as people will probably not want to keep reading once it's up and running? (Maybe just add a line about getting the AWS credentials sorted)

2023-03-15 11:43 UTC, andrewrae5-nhs commented on README.md
> +nrlf terraform plan <yourname>-test
Make sure terraform is installed! Add onto the install reqs 😅

2023-03-15 11:43 UTC, andrewrae5-nhs commented on README.md
> +nrlf terraform plan <yourname>-test
the commends i used are in the terraform docs [here](https://developer.hashicorp.com/terraform/downloads), but the main commands are:
```
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
 echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
 sudo apt update && sudo apt install terraform
```

2023-03-15 11:44 UTC, andrewrae5-nhs commented on README.md
> +add to bashrc - export PATH="/yourHomeDirectory/.local/bin:$PATH" spineVM home dir is "/home/spineii-user/"
quick update - check out my comment on line 70 - you can just replicate that styling i put in the comment

2023-03-16 11:33 UTC, merged