[NRLF-644] errors in swagger consumer
NHSDigital/NRLF pull request #462
Opened 2023-08-10 14:01 UTC by jameslinnell

2023-08-14 12:40 UTC, nomad3k requested changes
The `/_count` endpoint is missing the Errors, because this is the only endpoint that resides in it's own swagger file.

2023-08-17 11:05 UTC, nomad3k approved these changes

2023-08-30 13:22 UTC, axelkrastek1-nhs commented on api/consumer/swagger.yaml
> +        "4xx":
Should this be uppercase as well?

2023-08-30 13:22 UTC, axelkrastek1-nhs commented on api/consumer/record-locator/consumer.yaml
> +        "4xx":
Should this be uppercase as well?

2023-08-30 13:22 UTC, axelkrastek1-nhs commented on swagger/consumer-static/count.yaml
> +        "4xx":
Should this be uppercase as well?

2023-09-13 13:53 UTC, merged