NRL-1215 duplicate fields tests
NHSDigital/NRLF pull request #790
Opened 2024-12-31 14:38 UTC by axelkrastek1-nhs

2025-01-02 16:57 UTC, katebobyn-nhs commented on tests/features/steps/2_request.py
> +            doc_ref_id = context.response.headers["Location"].split("/")[-1]
why is this needed for upsert? we already know what the ID is if we're upserting

2025-01-02 17:01 UTC, katebobyn-nhs commented on tests/features/utils/data.py
> +    }}"""
When this is called it says "with duplicate {section} section", but for every possible section we add a duplicate CONTENT section. If this is intended can we clarify and/or rename things? It's confusing IMO

2025-01-24 09:59 UTC, eesa456 requested changes

2025-01-24 09:59 UTC, eesa456 commented on tests/features/producer/upsertDocumentReference-failure.feature
> +        "diagnostics": "Invalid practice setting coding: display Ophthalmology service does not match the expected display for 788002001 Practice Setting coding is bound to value set https://fhir.nhs
for reference these need to be changed once the fix is in correct? maybe a comment saying that at the top of the test?

2025-01-24 09:59 UTC, eesa456 commented on tests/features/steps/2_request.py
> +            doc_ref_id = context.response.headers["Location"].split("/")[-1]
true could easily reserve this to post requests only, doesnt make too much of a difference but kinda makes more sense than getting it from the location (either way i dont mind as its so small of a difference)

2025-01-24 09:59 UTC, eesa456 commented on tests/features/steps/2_request.py
> +    if request_type == "upsert":
this is a post only method? unless you wanna rename the function to be more like "create post and put body with duplicate section step"

2025-01-24 11:15 UTC, axelkrastek1-nhs commented
This PR is no longer valid, closing in favor of https://github.com/NHSDigital/NRLF/pull/801

2025-01-24 11:15 UTC, closed without merging